// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1Zm9eAYrpt9XjCO4gRtetK4D2CVzpxU',
    appId: '1:563408458274:android:dd8eba2673d29b87fbb07b',
    messagingSenderId: '563408458274',
    projectId: 'ledger-finance-app-49bdc',
    storageBucket: 'ledger-finance-app-49bdc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVH0RhCU1jSIO3A5OHGGhCvf0Ul9SrYg',
    appId: '1:563408458274:ios:10d1850084d0d351fbb07b',
    messagingSenderId: '563408458274',
    projectId: 'ledger-finance-app-49bdc',
    storageBucket: 'ledger-finance-app-49bdc.firebasestorage.app',
    androidClientId: '563408458274-6ls334cfilcjdq4hrs0qnaf2jcs8r9oe.apps.googleusercontent.com',
    iosClientId: '563408458274-2ioqj90av93gbtqltv15emu0v9a6or7v.apps.googleusercontent.com',
    iosBundleId: 'com.dhruv.ledgerMobile',
  );
}
